### PR TITLE
Added visibility to default transitions

### PR DESCRIPTION
**Pull request by GraxMonzo**

### CODE REVIEW

**Comment by benface** [comment]
@GraxMonzo Can you please provide me with an example (Codepen or similar) of `visibility` being transitioned? From what I'm reading online it doesn't seem like a transitionable property.

**Comment by GraxMonzo** [comment]
@benface https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties

**Comment by benface** [comment]
@GraxMonzo Right, but when is that ever useful?

**Comment by GraxMonzo** [comment]
I think there should be way to combine 2 properties

**Comment by GraxMonzo** [comment]
visibility and opacity

**Pull request closed without merging**
